/*
 * config.cpp -- Implementation of config file parsing.
 *
 * Config file location: same directory as winmm.dll (the FF7 install folder).
 * File name: ffvii_accessibility.cfg
 * Format: one key=value pair per line, # comments, blank lines ignored.
 * Keys are case-insensitive. Boolean values: "true"/"1" = true, anything else = false.
 */

#include "config.h"
#include "default_config.h"   // generated by CMake from the canonical
                              // AccessibilityMod/ffvii_accessibility.cfg

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include <fstream>
#include <string>
#include <algorithm>
#include <cctype>

namespace Config {

namespace {
    // The one global settings instance. Populated by Load(), read by Get().
    Settings g_settings;

    // Strips leading and trailing whitespace from a string in-place.
    void trim(std::string& s) {
        const auto not_space = [](unsigned char c) { return !std::isspace(c); };
        s.erase(s.begin(), std::find_if(s.begin(), s.end(), not_space));
        s.erase(std::find_if(s.rbegin(), s.rend(), not_space).base(), s.end());
    }

    // Returns true if the value string represents a truthy config value.
    // Truthy: "true" (case-insensitive), "1", "yes".
    bool parse_bool(const std::string& value) {
        std::string v = value;
        std::transform(v.begin(), v.end(), v.begin(),
            [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        return (v == "true" || v == "1" || v == "yes");
    }

    // v2.30.39: create the default config file when none exists, so a user
    // who deletes (or never receives) the cfg gets the fully documented
    // canonical file — settings list at the top, glossary below — instead
    // of an invisible all-defaults state. The content is the repo's own
    // ffvii_accessibility.cfg, embedded at build time (default_config.h,
    // generated by CMake — see CMakeLists.txt), so this write can never
    // drift from the committed file.
    //
    // Best-effort by design: if the install folder is not writable (e.g.
    // Program Files without elevation), the open fails and we silently run
    // on compiled defaults — exactly the pre-v2.30.39 behavior. A partial
    // write (disk full) is also harmless: the next launch parses whatever
    // half exists, and every value in the file IS the compiled default.
    //
    // Line endings: the embedded bytes are written through TEXT mode with
    // any '\r' stripped first, so '\n' expands to CRLF exactly once no
    // matter how git checked the source file out (LF or CRLF) — Windows
    // users always get a Notepad-friendly CRLF file.
    void write_default_config(const std::string& path) {
        std::ofstream out(path);          // text mode: '\n' -> CRLF
        if (!out.is_open()) return;
        for (size_t i = 0; i < kDefaultConfigSize; ++i) {
            const char c = static_cast<char>(kDefaultConfigBytes[i]);
            if (c != '\r') out.put(c);
        }
    }
} // anonymous namespace

void Load()
{
    // Find the directory containing this DLL so we can locate the config file
    // next to it. GetModuleFileNameA with a NULL HMODULE would give the EXE path.
    // We need to pass our own HMODULE. We obtain it via a dummy call to
    // GetModuleHandleExA using the address of this function as an anchor —
    // this is the standard portable pattern for a DLL to find its own path.
    HMODULE hSelf = NULL;
    GetModuleHandleExA(
        GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
        reinterpret_cast<LPCSTR>(&Load),
        &hSelf
    );

    char dll_path[MAX_PATH] = {};
    GetModuleFileNameA(hSelf, dll_path, MAX_PATH);

    // Strip the DLL filename to get just the directory.
    // e.g. "C:\Games\FF7\winmm.dll" → "C:\Games\FF7\"
    std::string config_path(dll_path);
    const size_t last_sep = config_path.find_last_of("\\/");
    if (last_sep != std::string::npos) {
        config_path = config_path.substr(0, last_sep + 1);
    }
    config_path += "ffvii_accessibility.cfg";

    // If the config file doesn't exist, create the documented default file
    // (v2.30.39) and keep the compiled defaults — which are, by
    // construction, the same values the file we just wrote contains, so
    // there is nothing to parse on this first run.
    std::ifstream file(config_path);
    if (!file.is_open()) {
        write_default_config(config_path);
        return;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Strip comments (everything from # onward).
        const size_t comment_pos = line.find('#');
        if (comment_pos != std::string::npos) {
            line = line.substr(0, comment_pos);
        }
        trim(line);
        if (line.empty()) continue;

        // Split on the first '=' to get key and value.
        const size_t eq_pos = line.find('=');
        if (eq_pos == std::string::npos) continue;

        std::string key   = line.substr(0, eq_pos);
        std::string value = line.substr(eq_pos + 1);
        trim(key);
        trim(value);
        if (key.empty()) continue;

        // Lowercase the key for case-insensitive matching.
        std::transform(key.begin(), key.end(), key.begin(),
            [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

        if      (key == "speak_dialog")  g_settings.speak_dialog  = parse_bool(value);
        else if (key == "speak_choices") g_settings.speak_choices = parse_bool(value);
        else if (key == "speak_battle")  g_settings.speak_battle  = parse_bool(value);
        else if (key == "speak_battle_menu") g_settings.speak_battle_menu = parse_bool(value);
        else if (key == "speak_menus")   g_settings.speak_menus   = parse_bool(value);
        else if (key == "speak_enemy_hp_always") g_settings.speak_enemy_hp_always = parse_bool(value);
        else if (key == "wall_bump_tone") g_settings.wall_bump_tone = parse_bool(value);
        else if (key == "proximity_tone") g_settings.proximity_tone = parse_bool(value);
        else if (key == "dialog_wait_tone") g_settings.dialog_wait_tone = parse_bool(value);
        else if (key == "dialog_choice_tone") g_settings.dialog_choice_tone = parse_bool(value);
        else if (key == "timer_announcements") g_settings.timer_announcements = parse_bool(value);
        // "field_exit_scan" was the pathfinder's short-lived original name
        // (v2.14, same-day rename) — accepted as an alias so no config breaks.
        else if (key == "pathfinder_keys" || key == "field_exit_scan")
            g_settings.pathfinder_keys = parse_bool(value);
        // direction_style takes a WORD, not a boolean: "turns" (default,
        // v2.22 walkmesh turn-by-turn) or "line" (as-the-crow-flies).
        // Unrecognized words keep the default rather than silently picking
        // a style the user did not ask for — same forward-compatibility
        // stance as unknown keys.
        else if (key == "direction_style") {
            std::string v = value;
            std::transform(v.begin(), v.end(), v.begin(),
                [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
            if (v == "line" || v == "straight" || v == "crow")
                g_settings.turn_by_turn = false;
            else if (v == "turns" || v == "turn_by_turn" || v == "path")
                g_settings.turn_by_turn = true;
        }
        else if (key == "gamepad_nav")   g_settings.gamepad_nav    = parse_bool(value);
        else if (key == "announce_map_change")
            g_settings.announce_map_change = parse_bool(value);
        else if (key == "interrupt")     g_settings.interrupt      = parse_bool(value);
        else if (key == "debug_log")     g_settings.debug_log      = parse_bool(value);
        // Unknown keys are silently ignored for forward compatibility.
    }
}

const Settings& Get()
{
    return g_settings;
}

} // namespace Config
