/*
 * config.cpp -- Implementation of config file parsing.
 *
 * Config file location: same directory as winmm.dll (the FF7 install folder).
 * File name: ffvii_accessibility.cfg
 * Format: one key=value pair per line, # comments, blank lines ignored.
 * Keys are case-insensitive. Boolean values: "true"/"1" = true, anything else = false.
 */

#include "config.h"
#include "default_config.h"   // generated by CMake from the canonical
                              // AccessibilityMod/ffvii_accessibility.cfg

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include <fstream>
#include <string>
#include <algorithm>
#include <cctype>
#include <cstdlib>    // strtol — tone_volume numeric parse (v2.30.41)
#include <vector>     // SaveSetting's line buffer (v2.30.42)

namespace Config {

namespace {
    // The one global settings instance. Populated by Load(), read by Get().
    Settings g_settings;

    // Strips leading and trailing whitespace from a string in-place.
    void trim(std::string& s) {
        const auto not_space = [](unsigned char c) { return !std::isspace(c); };
        s.erase(s.begin(), std::find_if(s.begin(), s.end(), not_space));
        s.erase(std::find_if(s.rbegin(), s.rend(), not_space).base(), s.end());
    }

    // Returns true if the value string represents a truthy config value.
    // Truthy: "true" (case-insensitive), "1", "yes".
    bool parse_bool(const std::string& value) {
        std::string v = value;
        std::transform(v.begin(), v.end(), v.begin(),
            [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        return (v == "true" || v == "1" || v == "yes");
    }

    // v2.30.39: create the default config file when none exists, so a user
    // who deletes (or never receives) the cfg gets the fully documented
    // canonical file — settings list at the top, glossary below — instead
    // of an invisible all-defaults state. The content is the repo's own
    // ffvii_accessibility.cfg, embedded at build time (default_config.h,
    // generated by CMake — see CMakeLists.txt), so this write can never
    // drift from the committed file.
    //
    // Best-effort by design: if the install folder is not writable (e.g.
    // Program Files without elevation), the open fails and we silently run
    // on compiled defaults — exactly the pre-v2.30.39 behavior. A partial
    // write (disk full) is also harmless: the next launch parses whatever
    // half exists, and every value in the file IS the compiled default.
    //
    // Line endings: the embedded bytes are written through TEXT mode with
    // any '\r' stripped first, so '\n' expands to CRLF exactly once no
    // matter how git checked the source file out (LF or CRLF) — Windows
    // users always get a Notepad-friendly CRLF file.
    void write_default_config(const std::string& path) {
        std::ofstream out(path);          // text mode: '\n' -> CRLF
        if (!out.is_open()) return;
        for (size_t i = 0; i < kDefaultConfigSize; ++i) {
            const char c = static_cast<char>(kDefaultConfigBytes[i]);
            if (c != '\r') out.put(c);
        }
    }

    // Full path of ffvii_accessibility.cfg, next to this DLL. Factored out
    // of Load() in v2.30.42 because SaveSetting() needs the identical path
    // — two copies of the own-module-directory dance would eventually
    // drift. Empty string on failure.
    std::string config_file_path() {
        HMODULE hSelf = NULL;
        GetModuleHandleExA(
            GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            reinterpret_cast<LPCSTR>(&config_file_path),
            &hSelf);

        char dll_path[MAX_PATH] = {};
        if (!GetModuleFileNameA(hSelf, dll_path, MAX_PATH)) return {};

        std::string path(dll_path);
        const size_t last_sep = path.find_last_of("\\/");
        if (last_sep != std::string::npos) {
            path = path.substr(0, last_sep + 1);
        }
        path += "ffvii_accessibility.cfg";
        return path;
    }
} // anonymous namespace

void Load()
{
    // Locate the config file next to this DLL (own-module-directory
    // pattern — see config_file_path() above, factored out in v2.30.42).
    const std::string config_path = config_file_path();
    if (config_path.empty()) return;   // keep compiled defaults

    // If the config file doesn't exist, create the documented default file
    // (v2.30.39) and keep the compiled defaults — which are, by
    // construction, the same values the file we just wrote contains, so
    // there is nothing to parse on this first run.
    std::ifstream file(config_path);
    if (!file.is_open()) {
        write_default_config(config_path);
        return;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Strip comments (everything from # onward).
        const size_t comment_pos = line.find('#');
        if (comment_pos != std::string::npos) {
            line = line.substr(0, comment_pos);
        }
        trim(line);
        if (line.empty()) continue;

        // Split on the first '=' to get key and value.
        const size_t eq_pos = line.find('=');
        if (eq_pos == std::string::npos) continue;

        std::string key   = line.substr(0, eq_pos);
        std::string value = line.substr(eq_pos + 1);
        trim(key);
        trim(value);
        if (key.empty()) continue;

        // Lowercase the key for case-insensitive matching.
        std::transform(key.begin(), key.end(), key.begin(),
            [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

        if      (key == "speak_dialog")  g_settings.speak_dialog  = parse_bool(value);
        else if (key == "speak_choices") g_settings.speak_choices = parse_bool(value);
        else if (key == "speak_battle")  g_settings.speak_battle  = parse_bool(value);
        else if (key == "speak_battle_damage") g_settings.speak_battle_damage = parse_bool(value);
        else if (key == "speak_battle_status") g_settings.speak_battle_status = parse_bool(value);
        else if (key == "speak_battle_menu") g_settings.speak_battle_menu = parse_bool(value);
        else if (key == "limit_reel_tone")  g_settings.limit_reel_tone  = parse_bool(value);
        else if (key == "limit_reel_speak") g_settings.limit_reel_speak = parse_bool(value);
        // limit_reel_tone_lead takes MILLISECONDS (0-1000); same strtol +
        // end-pointer + clamp treatment as tone_volume — a typo keeps the
        // compiled default rather than silently zeroing the lead.
        else if (key == "limit_reel_tone_lead") {
            char* end = nullptr;
            const long v = strtol(value.c_str(), &end, 10);
            if (end != value.c_str()) {
                g_settings.limit_reel_tone_lead =
                    static_cast<int>(v < 0 ? 0 : (v > 1000 ? 1000 : v));
            }
        }
        else if (key == "speak_menus")   g_settings.speak_menus   = parse_bool(value);
        else if (key == "speak_enemy_hp_always") g_settings.speak_enemy_hp_always = parse_bool(value);
        else if (key == "wall_bump_tone") g_settings.wall_bump_tone = parse_bool(value);
        else if (key == "proximity_tone") g_settings.proximity_tone = parse_bool(value);
        else if (key == "proximity_announce") g_settings.proximity_announce = parse_bool(value);
        else if (key == "dialog_wait_tone") g_settings.dialog_wait_tone = parse_bool(value);
        else if (key == "dialog_choice_tone") g_settings.dialog_choice_tone = parse_bool(value);
        else if (key == "timer_announcements") g_settings.timer_announcements = parse_bool(value);
        // "field_exit_scan" was the pathfinder's short-lived original name
        // (v2.14, same-day rename) — accepted as an alias so no config breaks.
        else if (key == "pathfinder_keys" || key == "field_exit_scan")
            g_settings.pathfinder_keys = parse_bool(value);
        // direction_style takes a WORD, not a boolean: "turns" (default,
        // v2.22 walkmesh turn-by-turn) or "line" (as-the-crow-flies).
        // Unrecognized words keep the default rather than silently picking
        // a style the user did not ask for — same forward-compatibility
        // stance as unknown keys.
        else if (key == "direction_style") {
            std::string v = value;
            std::transform(v.begin(), v.end(), v.begin(),
                [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
            if (v == "line" || v == "straight" || v == "crow")
                g_settings.turn_by_turn = false;
            else if (v == "turns" || v == "turn_by_turn" || v == "path")
                g_settings.turn_by_turn = true;
        }
        // tone_volume takes a NUMBER (0-100), not a boolean. strtol with an
        // end-pointer check so garbage ("loud", "") keeps the compiled
        // default instead of atoi's silent 0 — a typo must not mute every
        // tone in the mod (same keep-the-default stance as direction_style).
        // Out-of-range numbers clamp rather than reject: the user's intent
        // ("150" = loud, "-5" = off) is unambiguous.
        else if (key == "tone_volume") {
            char* end = nullptr;
            const long v = strtol(value.c_str(), &end, 10);
            if (end != value.c_str()) {
                g_settings.tone_volume =
                    static_cast<int>(v < 0 ? 0 : (v > 100 ? 100 : v));
            }
        }
        else if (key == "gamepad_nav")   g_settings.gamepad_nav    = parse_bool(value);
        else if (key == "announce_map_change")
            g_settings.announce_map_change = parse_bool(value);
        else if (key == "interrupt")     g_settings.interrupt      = parse_bool(value);
        else if (key == "debug_log")     g_settings.debug_log      = parse_bool(value);
        // Unknown keys are silently ignored for forward compatibility.
    }
}

const Settings& Get()
{
    return g_settings;
}

Settings& GetMutable()
{
    // Single-writer contract documented in config.h: the settings-menu
    // thread is the only caller allowed to WRITE through this reference.
    return g_settings;
}

bool SaveSetting(const char* key, const char* value)
{
    if (!key || !value) return false;
    const std::string path = config_file_path();
    if (path.empty()) return false;

    // Read the whole file as lines. Text mode strips CRLF on the way in;
    // the rewrite below re-expands '\n' to CRLF, so the file stays
    // Notepad-friendly regardless of how it was created.
    std::vector<std::string> lines;
    {
        std::ifstream in(path);
        if (!in.is_open()) {
            // Cfg deleted mid-session: recreate the canonical default
            // (same behavior as Load() on first run), then edit that.
            write_default_config(path);
            in.open(path);
            if (!in.is_open()) return false;   // unwritable directory
        }
        std::string line;
        while (std::getline(in, line)) lines.push_back(line);
    }

    // Find the first ACTIVE assignment line for this key: optional leading
    // whitespace, the key (case-insensitive), optional whitespace, '='.
    // Commented glossary lines start with '#' and can never match, which
    // is exactly the v2.30.39 rule (glossary must stay inert).
    std::string want(key);
    std::transform(want.begin(), want.end(), want.begin(),
        [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    size_t match = lines.size();
    for (size_t i = 0; i < lines.size(); ++i) {
        const std::string& l = lines[i];
        size_t p = 0;
        while (p < l.size() && std::isspace(static_cast<unsigned char>(l[p]))) ++p;
        if (p + want.size() > l.size()) continue;
        bool eq = true;
        for (size_t k = 0; k < want.size(); ++k) {
            if (std::tolower(static_cast<unsigned char>(l[p + k])) != want[k]) {
                eq = false;
                break;
            }
        }
        if (!eq) continue;
        size_t q = p + want.size();
        while (q < l.size() && std::isspace(static_cast<unsigned char>(l[q]))) ++q;
        if (q < l.size() && l[q] == '=') {
            match = i;
            break;
        }
    }

    const std::string assignment = std::string(key) + " = " + value;
    if (match < lines.size()) {
        // Replace the line wholesale. Any trailing same-line comment is
        // dropped — the canonical top list has none (descriptions live in
        // the glossary), and a hand-added one describing the OLD value
        // would be exactly the stale-comment hazard we avoid elsewhere.
        lines[match] = assignment;
    } else {
        // No active line (hand-trimmed or ancient cfg): append at the end,
        // where last-one-wins parsing guarantees it takes effect.
        lines.push_back("");
        lines.push_back("# Set by the in-game accessibility menu (F8):");
        lines.push_back(assignment);
    }

    // Rewrite in place. A crash mid-write could truncate the file, but the
    // exposure is a handful of milliseconds for a ~17 KB file, the mod
    // recreates the canonical default on the next launch if the file is
    // lost, and a temp+rename dance would double the failure modes in the
    // one directory (Program Files) where creating extra files is most
    // likely to be denied. Simple rewrite is the right trade here.
    std::ofstream out(path, std::ios::trunc);
    if (!out.is_open()) return false;
    for (const std::string& l : lines) out << l << '\n';
    return out.good();
}

} // namespace Config
