/*
 * config.h -- User configuration for the FF7 accessibility mod.
 *
 * Configuration is read from "ffvii_accessibility.cfg" in the same directory
 * as this DLL (the FF7 install folder). The file uses a simple key=value
 * format with # for comments.
 *
 * If the config file does not exist, all settings use their defaults AND
 * the canonical default file is created next to the DLL (v2.30.39) —
 * settings list at the top, glossary of descriptions below. The written
 * content is the repo's ffvii_accessibility.cfg, embedded at build time
 * (default_config.h, generated by CMake), so it cannot drift.
 * Unknown keys are ignored silently to allow forward compatibility.
 */

#pragma once

// Mod version, stamped into the debug log header (v2.30.81). Until now no
// artifact in a play-test log said WHICH build produced it -- diagnosing the
// 2026-08-04 station report meant inferring the deployed version from file
// timestamps. One constant, bumped per release alongside the commit tag.
#define FF7ACCESS_VERSION "2.30.89"

namespace Config {

// All mod settings are stored in this struct. One global instance is populated
// by Load() and read by all hook functions.
struct Settings {
    // speak_dialog: If true, story dialog text (MESSAGE opcode) is read aloud
    // by the screen reader. Set to false if you have a voice acting mod
    // installed and prefer the voice actors over TTS.
    //
    // v2.30.45: SPEAKER-LESS system messages (item pick-ups, "Received X")
    // speak regardless of this setting — voice mods never voice those, so
    // muting them with the story text left pick-ups silent in the
    // voice-mod configuration (see hooks.cpp LooksLikeCharacterSpeech).
    // Default: true.
    bool speak_dialog = true;

    // speak_choices: If true, choice menu options (ASK opcode) are read aloud
    // as the cursor moves between them. Recommended true even when speak_dialog=false,
    // since choices require acknowledgement and voice mods typically do not
    // cover every choice line.
    // Default: true.
    bool speak_choices = true;

    // speak_battle: If true, battle action text is read aloud (attack names,
    // spell names, item use text). Default: true.
    bool speak_battle = true;

    // speak_battle_damage: If true, HP changes in battle are spoken
    // (v2.30.84, user request; v2.30.89 rework, user request). A sighted
    // player gets a floating number over whoever was struck; this speaks
    // that number COMBINED with the action that caused it, one line per
    // action so the player hears what attacked, whom, and the cost
    // together: "MP 1, Machine Gun, Cloud minus 96 HP." / "Cloud, Cure,
    // Barret plus 200 HP.", with ", N left" appended only when a hit
    // leaves a party member at or below a quarter of max HP (the moment
    // the sighted HP readout turns yellow — the one time remaining HP is
    // urgent enough to spend words on). Out-of-turn changes (poison and
    // regen ticks) speak on their own ("Cloud minus 10 HP.").
    // Separate from speak_battle so a player who finds the numbers chatty
    // can silence just them and keep bare action names.
    // Default: true.
    bool speak_battle_damage = true;

    // speak_battle_status: If true, status effects gained or cured in
    // battle are spoken by name, riding the same combined action line as
    // the damage numbers (v2.30.89, user request): "MP 1, Bio, Cloud
    // minus 50 HP, poison." / "Cloud, Esuna, Barret, poison removed."
    // Death and near-death are excluded — the defeat/"is down" watcher
    // and the ", N left" warning own those moments respectively.
    // Default: true.
    bool speak_battle_status = true;

    // speak_battle_menu: If true, the in-battle command menu is announced as
    // the cursor moves: command names (Attack/Magic/Item/Limit...), magic and
    // item list entries by name, and target selection ("enemy 1", ally names).
    // This is the navigation half of battle TTS; speak_battle covers the
    // action-execution half (what actually happens each turn). Separate flags
    // because a player may want quiet menus but spoken actions, or vice versa.
    // Default: true.
    bool speak_battle_menu = true;

    // speak_menus: If true, menu navigation is announced. Covers the title
    // screen cursor, main menu cursor + Quit dialog, Config sub-menu rows and
    // values, Sound sub-menu cursor and volumes, and the name-entry screen
    // (grid cursor + name readback). Default: true.
    bool speak_menus = true;

    // speak_enemy_hp_always: If true, target selection speaks enemy HP even
    // when the enemy has NOT been Sensed. By default (false) enemy HP is only
    // spoken once Sense has revealed it — exact information parity with the
    // sighted target window, which hides enemy HP until Sense. Enable this if
    // you prefer full HP info over parity (or for testing before Sense is
    // available). Party HP is always spoken regardless of this setting.
    // Default: false.
    bool speak_enemy_hp_always = false;

    // pathfinder_keys: If true, the FF1-6 accessibility-scheme pathfinder
    // hotkeys work during field gameplay (see accessiblity_keys.txt at the
    // repo root — key parity with the FF4 screen-reader mod is a project
    // requirement): J/L or [/] cycle destinations, Shift+J/L or -/= cycle
    // categories, K announces the selection, Shift+K resets to All, \ or P
    // speaks direction + walking distance, M announces the map name. Keys
    // only respond while the game window is focused and the player is in
    // normal field control (not in menus, battles, or dialogs).
    // Default: true.
    bool pathfinder_keys = true;

    // turn_by_turn: Direction style for the pathfinder's directions key
    // (\ or P, or R3 on the controller). Set from the config file's
    // direction_style key — "turns" (true) or "line" (false):
    //
    //   turns — v2.22 turn-by-turn route over the field's walkmesh:
    //           "Exit 2: up 4 seconds, then right 2 seconds". Computed by
    //           pathfinding the walkable triangle graph, so it routes
    //           around walls and pits instead of pointing through them.
    //           When no walkable route exists (or the walkmesh cannot be
    //           read), it automatically falls back to the straight-line
    //           announcement — same graceful degradation the FF4
    //           screen-reader mod documents for out-of-range targets.
    //   line  — the original as-the-crow-flies announcement: one bearing
    //           and the straight-line walking time ("Exit 2: up-left,
    //           3 seconds"). Some players prefer the shorter message and
    //           re-querying while walking.
    //
    // Default: true (turns).
    bool turn_by_turn = true;

    // announce_map_change: If true, the mod announces "Screen: <name>"
    // whenever the player crosses to a new field screen (v2.23). Each FF7
    // screen has its own fixed camera, so crossing an exit REBASES what
    // "up" means — a sighted player sees the camera cut; this announcement
    // is the audio equivalent, cueing that all directions just changed
    // their meaning. Since v2.24 the name is the game's own friendly menu
    // caption ("Sector 1 Station", the MPNAM buffer), falling back to the
    // internal map name when no caption is set yet.
    // Default: true.
    bool announce_map_change = true;

    // gamepad_nav: If true, the RIGHT ANALOG STICK of an XInput controller
    // drives the pathfinder alongside the keyboard (v2.21): flick up/down to
    // change category, left/right to cycle destinations, click the stick in
    // (R3) for directions. Same gates as pathfinder_keys (game focused,
    // normal field control), and pathfinder_keys=false disables this too —
    // the stick is a second set of triggers for the same browser, not a
    // separate feature. Safe by construction: FF7 itself never reads the
    // right stick, and R3 is unbound in the game's joystick config (see
    // gamepad.h for the full evidence trail).
    // Default: true.
    bool gamepad_nav = true;

    // proximity_tone: If true, a single short high chirp (1175 Hz) fires
    // the moment the player comes within INTERACTION RANGE of something
    // usable (v2.27): a talkable person (their actual talk radius, the
    // same circle the game tests when OK is pressed — people flagged
    // talk-disabled stay silent), a chest / item / save point, or a
    // trigger line (ladder, elevator). Fires ONCE per approach: it
    // re-arms only after walking away, so standing next to someone stays
    // quiet but coming back pings again. Distinct from the 220 Hz wall
    // tone and the 880 Hz wandering cue.
    // Default: true.
    bool proximity_tone = true;

    // proximity_announce: If true, coming within interaction range also
    // SPEAKS what you reached — "Ladder up", "Biggs", "Chest", "Save
    // point" — not just the proximity_tone chirp (v2.30.62, user
    // request). Separate switch because the two serve different tastes:
    // the chirp is unobtrusive and language-free for a player who
    // already knows the room, while the spoken name answers "what did I
    // just walk up to?" for a first visit. Uses the SAME range test and
    // once-per-approach arming as the chirp, so enabling both gives one
    // chirp plus one name, never a stream.
    // Default: true.
    bool proximity_announce = true;

    // timer_announcements: If true, an active field countdown timer (timed
    // escapes — first one: the No.1 Reactor run) announces itself: start,
    // each minute boundary, the 30-second mark, and a spoken countdown over
    // the final 10 seconds. The T key (announce time left on demand) and
    // Shift+T (freeze toggle) work regardless of this setting — this only
    // controls the AUTOMATIC announcements. Default: true.
    bool timer_announcements = true;

    // dialog_wait_tone: If true, a short high tone (1568 Hz) plays the
    // moment a story dialog finishes displaying its current text and is
    // sitting there waiting for you to press the confirm button — whether
    // that press will turn a page, close the box, or advance to the next
    // line. Distinct from every other tone in this mod (220 Hz wall thud,
    // 880 Hz wandering cue, 1175 Hz proximity chirp). Independent of
    // speak_dialog, so it still fires for players who rely on a voice
    // acting mod instead of our TTS narration.
    // Default: true.
    bool dialog_wait_tone = true;

    // dialog_choice_tone: If true, a short high DOUBLE tone (two quick
    // 1568 Hz beeps) plays the instant a choice menu (ASK opcode) is
    // presented — a separate cue from dialog_wait_tone's single tone, so
    // the two are distinguishable by ear alone. Independent of
    // speak_choices for the same reason dialog_wait_tone is independent of
    // speak_dialog.
    // Default: true.
    bool dialog_choice_tone = true;

    // wall_bump_tone: If true, a short low tone plays while the player pushes
    // against a wall or obstacle on a field map (direction held but the
    // character is not moving). Vanilla FF7 has no footstep sounds, so without
    // this there is no audio cue distinguishing "walking" from "stuck on a
    // wall" — a blind player can walk against a wall indefinitely without
    // knowing. The tone repeats every ~300ms for as long as contact continues.
    // Default: true.
    bool wall_bump_tone = true;

    // tone_volume: Loudness of ALL the mod's audio cues (wall thud,
    // proximity chirp, wandering cue, dialog wait/choice tones) on a 0-100
    // scale. Exists since v2.30.41, when tone playback moved from kernel32
    // Beep() (fixed loudness, silently broken in VMs/remote sessions) to a
    // waveOut stream on the default audio device (tones.cpp). 0 silences
    // every tone without touching the individual tone switches; the
    // per-tone bools above still control WHICH cues fire. Values outside
    // 0-100 are clamped at load.
    // Default: 60 (chosen to sit near Beep()'s perceived loudness).
    int tone_volume = 60;

    // interrupt: If true, new TTS output interrupts currently-playing speech.
    // In menus and dialog, this gives faster, more responsive feedback.
    // Set to false if your screen reader handles queuing better than interruption.
    // Default: true.
    bool interrupt = true;

    // debug_log: If true, all [FF7Access] diagnostic messages are written to
    // ffvii_accessibility.log in the FF7 install folder. The log file is
    // overwritten each session so it contains only the most recent run.
    //
    // Enable this when reporting a bug: reproduce the issue, then send the
    // ffvii_accessibility.log file alongside your bug report.
    //
    // Default: true FOR THE TEST PERIOD (user decision 2026-07-31: the mod
    // is considered a test mod until further notice, and every tester
    // report so far was only diagnosable because a log existed — the
    // v2.30.41 silent tones and the v2.30.43 scorpion crash both hinged on
    // session logs). Revert to false when the mod leaves its test phase.
    bool debug_log = true;
};

// Load reads ffvii_accessibility.cfg from the DLL's own directory.
// Sets all fields of the global Settings instance.
// Safe to call from DllMain on a background thread.
void Load();

// Get returns a const reference to the active settings.
//
// Settings were strictly read-only after Load() until v2.30.42; the F8
// in-game accessibility menu now mutates them at runtime through
// GetMutable() below. Consumers need no changes: every reader already
// re-reads Config::Get().<field> at its point of use (audited 2026-07-31
// while building the menu — that audit is what makes live application
// work with no restart), and every field is a bool or int, 4-byte-or-
// smaller and naturally aligned, so a concurrent read sees either the
// old or the new value — never a torn one — on x86.
const Settings& Get();

// GetMutable returns the same global instance writable. SINGLE-WRITER
// CONTRACT: only the settings-menu thread (settings_menu.cpp) may write,
// and only one such thread exists — that is what makes the lock-free
// x86 word-write model above sound. Do not write from hooks or other
// polling threads; add a proper lock first if a second writer ever
// becomes necessary.
Settings& GetMutable();

// SaveSetting rewrites ONE key's value inside ffvii_accessibility.cfg,
// preserving every other byte of the file (user comments, the glossary,
// formatting). Strategy: replace the first ACTIVE (uncommented)
// "key = ..." line; if the key has no active line (hand-trimmed or
// pre-v2.30.39 cfg), append "key = value" at the end of the file, which
// wins because the parser is last-one-wins. If the cfg is missing
// entirely, the canonical default file is created first, then edited.
// Returns false when the file cannot be written (read-only install dir)
// — the in-memory change still applies for the session; callers should
// tell the user the change will not survive a restart.
// Called from the settings-menu thread only.
bool SaveSetting(const char* key, const char* value);

} // namespace Config
